#!/bin/bash
#Simple bash script that finds an integer average

num=0
count=0
sum=0
exit=-999999

echo "Enter numbers to get an average."
echo Enter $exit to finish

read -p "num: " num
while (( num != exit )); do
        ((count++))
        sum=$((sum+num))
        read -p "num: " num
done
